#!/bin/sh

PKG=$1

[ -d "$PKG" -o -f "$PKG.spec" ] || fedpkg clone -a $PKG

[ -d "$PKG" ] && cd $PKG

if [ -n "$2" ]; then
  fedpkg switch-branch $2
fi

sudo yum-builddep $PKG.spec
fedpkg local

TMP=test-tmp

rm -r $TMP/
mkdir $TMP/

cd $(arch)

PKGS=$(rpm -qp --qf "%{name}-%{version}\n" *)

sudo yum install $PKGS

for i in $PKGS; do
  for k in requires provides; do
    rpm -qp --$k $(ls -t $i*.rpm | head) > ../$TMP/$i.$k.test
    rpm -q --$k $i > ../$TMP/$i.$k.installed
    diff -u --exclude="rpmlib(FileDigests)" ../$TMP/$i.$k.installed ../$TMP/$i.$k.test > ../$k.$i.diff
  done
done
