#!/bin/sh

PKG=$1

[ -d "$PKG" -o -f "$PKG.spec" ] || fedpkg clone -a $PKG

[ -d "$PKG" ] && cd $PKG

if [ -n "$2" ]; then
  fedpkg switch-branch $2
fi

sudo yum builddep $PKG.spec
fedpkg local

mkdir -p test

cd $(arch)

PKGS=$(rpm -qp --qf "%{name}\n" *)

sudo yum install $PKGS

for i in $PKGS; do
  for k in requires provides; do
    rpm -qp --$k $(ls $i*.rpm | head) > ../test/$i.$k.test
    rpm -q --$k $i > ../test/$i.$k.installed
    diff -u ../test/$i.$k.installed ../test/$i.$k.test > ../$i.$k.diff
  done
done
